//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obs_test.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("obs_test.Domain.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to deserialize input data from JSON..
        /// </summary>
        public static string Error_DeserializeJSON {
            get {
                return ResourceManager.GetString("Error_DeserializeJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F].
        /// </summary>
        public static string Mark_FinalPosition_Short {
            get {
                return ResourceManager.GetString("Mark_FinalPosition_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  F  ].
        /// </summary>
        public static string Mark_FinalPositon {
            get {
                return ResourceManager.GetString("Mark_FinalPositon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  X  ].
        /// </summary>
        public static string Mark_VisitedCell {
            get {
                return ResourceManager.GetString("Mark_VisitedCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [X].
        /// </summary>
        public static string Mark_VisitedCell_Short {
            get {
                return ResourceManager.GetString("Mark_VisitedCell_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands: {0}.
        /// </summary>
        public static string Message_Commands {
            get {
                return ResourceManager.GetString("Message_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Position: [{0}, {1}], Facing: {2}.
        /// </summary>
        public static string Message_FinalPosition {
            get {
                return ResourceManager.GetString("Message_FinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: .
        /// </summary>
        public static string Message_GenericError {
            get {
                return ResourceManager.GetString("Message_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Position: [{0}, {1}], Facing: {2}.
        /// </summary>
        public static string Message_InitialPosition {
            get {
                return ResourceManager.GetString("Message_InitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is not valid.
        /// </summary>
        public static string Message_InvalidCommand {
            get {
                return ResourceManager.GetString("Message_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction is not valid.
        /// </summary>
        public static string Message_InvalidDirection {
            get {
                return ResourceManager.GetString("Message_InvalidDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Battery: {0}.
        /// </summary>
        public static string Message_RemainingBattery {
            get {
                return ResourceManager.GetString("Message_RemainingBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples Collected: {0}.
        /// </summary>
        public static string Message_SamplesCollected {
            get {
                return ResourceManager.GetString("Message_SamplesCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation complete. Output written to {0}.
        /// </summary>
        public static string Message_Simulation_Completed {
            get {
                return ResourceManager.GetString("Message_Simulation_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error: {0}.
        /// </summary>
        public static string Message_Validation_Error {
            get {
                return ResourceManager.GetString("Message_Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string Terrain {
            get {
                return ResourceManager.GetString("Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain Route (.
        /// </summary>
        public static string Terrain_Route {
            get {
                return ResourceManager.GetString("Terrain_Route", resourceCulture);
            }
        }
    }
}
